---
- name: Restart Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
  become: true


- name: Reload Prometheus config
  ansible.builtin.uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200
  register: prometheus_docker_reload_result
  # Handle Connection reset and retry
  until: prometheus_docker_reload_result.status == 200
  retries: 10   # Try up to 10 times
  delay: 1      # Wait 1 second between attempts
